#!/usr/bin/env python3
import os

base_address = 0x80400000
step = 0x20000
linker = 'src/linker.ld'

app_list = os.listdir('src/bin')
app_list.sort()

for app_id, app in enumerate(app_list):
    linker_script_content = []
    linker_script_backup = []
    with open(linker, 'r') as f:
        for line in f.readlines():
            linker_script_backup.append(line)
            line = line.replace(hex(base_address), hex(base_address+step*app_id))
            linker_script_content.append(line)

    with open(linker, 'w+') as f:
        f.writelines(linker_script_content)

    os.system(f'cargo build --bin {app[:-3]}')

    with open(linker, 'w+') as f:
        f.writelines(linker_script_backup)
